name: DanielMoscovitch
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25446
title: 'Producer, Musician, Educator'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#150b09'
    - '#c09c82'
    - '#6a5c41'
    - '#9b220f'
    - '#e9e9df'
  brandStrength: 0.5625
  lightness: 0.5625
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
