name: DanielMoscovitch
favicon: null
layout_spectrum: 0.25443
typography_spectrum: 0.25446
title: 'Producer, Musician, Educator'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060014'
    - '#f9f9f9'
    - '#bc23aa'
    - '#bab1ca'
    - '#6d6381'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
