name: Daniel Moscovitch
favicon: null
layout_spectrum: 0.37292
typography_spectrum: 0.55819
title: DANIEL MOSCOVITCH
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a191e'
    - '#f0f0f2'
    - '#83add5'
    - '#a06255'
    - '#098d5c'
  brandStrength: 0.125
  lightness: 0.4375
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
