name: DanielMoscovitch
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25446
title: 'Producer, Musician, Educator'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#526ba3'
    - '#141823'
    - '#f4006d'
    - '#4adb6c'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
