name: DanielMoscovitch
favicon: null
layout_spectrum: 0.06391530437394977
typography_spectrum: 0.8360159026924521
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4978713740129024
  lightness: 0.697757248301059
  saturation: 0.1959442705847323
  rhythmicContrast: 0.5716421331744641
purpose: []
