name: DanielMoscovitch
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25446
title: 'Producer, Musician, Educator'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#faf1f4'
    - '#001415'
    - '#b2b6c5'
    - '#fb8818'
    - '#e80000'
  brandStrength: 0.625
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
