typography_spectrum: 0.09464752115309238
color:
  saturation: 0.008084521861746907
  brandStrength: 0.4411288963165134
  lightness: 0.35352862044237554
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  rhythmicContrast: 0.6336082690395415
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6247925711795688
analytics:
  twitter: null
  google: null
  facebook: null
name: Daniel Moscovitch
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: Contact
    id: ac6d18dc-81c1-4d0d-955f-f57378c1e180
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: DANIEL MOSCOVITCH
description: Musician / Producer
purpose: []
